### ISSUE TITLE
Parsing time of VIAF results: test threshold too low

### ISSUE THREAD

**Issue by wetneb** [codeforkjeff/conciliator#14]
When running `mvn package` on my computer:
```
Failed tests: 
  VIAFParserTest.testParseTime:160 should take less than 50ms, on average, to parse a big XML doc, but took 52ms
```
I see you have added a special case for travis, I think it would make sense to use 100ms regardless of the environment.

Also: thank you so much for your implementation of the data extension API! It looks very exciting.

**Comment by codeforkjeff** [comment]
Okay, I've bumped it up to 150ms regardless of environment, since sometimes it fails on travis too.

Yes, I've been working on getting the data extension pieces modeled, but no data source uses it yet... I need to work on that, but I've been so busy (I moved across the country last year!). Hopefully soon...
