### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by wetneb** [codeforkjeff/conciliator#19]
The reconciliation endpoints are only available via JSONP at the moment. It would be great to enable it for CORS too.

We are currently planning to phase out JSONP in the reconciliation API: see https://github.com/reconciliation-api/specs/issues/19.

Support for CORS will be added in OpenRefine: https://github.com/OpenRefine/OpenRefine/issues/2260

**Comment by wetneb** [comment]
(I tried submitting a PR for this as a Xmas present but could not figure out how to make it work with Spring… sorry!)

**Comment by codeforkjeff** [comment]
Response headers for all the endpoints should now include `access-control-allow-origin: *`. Since JSONP still needs to be supported for compat with older versions of OpenRefine, I've left that code untouched: it is only triggered by the presence of the "callback" param so it shouldn't need any modification.

I did very basic tests with OpenRefine 2.8 and 3.3 and both seem to work with the service running on my local machine.

I'm not sure this is comprehensive enough though, my knowledge of CORS is pretty basic, so there might need to be other headers set?

**Comment by wetneb** [comment]
That's fantastic, thank you! Yes it makes sense to still support JSONP for older clients.
Your change looks great to me.
